name = "ControleOptimal"
uuid = "b13ffa8e-caa1-11ea-103b-171d11149a30"
authors = ["nsaloua <naamasaloua1998@gmail.com>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
